apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-configmap
  namespace: default
data:
  # MongoDB
  MONGO_URI: mongodb://mongo:27017/videos

  # RabbitMQ
  RABBITMQ_HOST: rabbitmq
  VIDEO_QUEUE: video
  MP3_QUEUE: mp3

  # Auth service (IMPORTANT FIX)
  AUTH_SVC_ADDRESS: auth:5000
